<?php

namespace HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AutoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoreRepository extends EntityRepository
{
    
    public function searchAutore($em,$autore){
       
        $aut=$this->findOneBy(array('nome'=>$autore->getNome(),'eta'=>$autore->getEta()));
       return $aut;
       
    }
    
    public function getAutoreById($idAutore){
        $autore=$this->find($idAutore);
        return $autore;
    }
}
