<?php

namespace HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OperaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperaRepository extends EntityRepository
{
    
    
    public function persistOpera($em,$opera){
        $em->persist($opera);
        $em->flush();
    }
    
    public function persistAutore($em,$autore){
        $em->persist($autore);
        $em->flush();
    }
    
    public function updateOpereInserite($em,$idUtente,$idOpera){
        
        //query sql per opere inserite
      $connection = $em->getConnection();
      //$statement = $connection->prepare("SELECT * FROM somethingelse WHERE id = :id");
     
      $statement = $connection->prepare("INSERT INTO opereinserite VALUES (NULL,$idUtente ,$idOpera)");
  
      $statement->execute();
      
     
        
    }
    
    public function getUserOpera($em,$idUtente){
          $connection = $em->getConnection();
          
            $statement = $connection->prepare("select *
                                                                                from (select titolo,tecnica,dimensioni,id_autore
                                                                                            from opereinserite op join opera o on op.id_opera=o.id
                                                                                            where id_utente=$idUtente) en join autore a on en.id_autore=a.id");
  
            $statement->execute();
            // result contiene tutte le opere inserite dall'utente con id = $idUtente
            $results = $statement->fetchAll();
            
            
            return $results;
          
    }
    
    
    public function getAuthors($em,$idUtente){
        
        $connection = $em->getConnection();
          
            $statement = $connection->prepare("SELECT distinct id,nome,eta
                                                                                FROM (SELECT id_autore
                                                                                              FROM (SELECT * 
                                                                                                            FROM opereinserite) op JOIN opera o on op.id_opera=o.id
                                                                                              WHERE id_utente=$idUtente ) opp JOIN autore a on opp.id_autore=a.id");
  
            $statement->execute();
            // result contiene tutte le opere inserite dall'utente con id = $idUtente
            $results = $statement->fetchAll();
            
            
            return $results;
        
    }
    
    public function getTabella($em,$tabella){
        $connection = $em->getConnection();
            
            $statement = $connection->prepare("SELECT * FROM $tabella");
            //$statement = $connection->prepare("SHOW TABLES FROM test");
            $statement->execute();
           
            // result contiene tutte le opere inserite dall'utente con id = $idUtente
            $results = $statement->fetchAll();
           
            
            return $results;
        
    }
    
    public function showTablesDb($em){
         $connection = $em->getConnection();
            
            $statement = $connection->prepare("SHOW TABLES FROM test");
            
            $statement->execute();
           
            // result contiene tutte le opere inserite dall'utente con id = $idUtente
            $results = $statement->fetchAll();
           
            
            return $results;
    }
    
    
    public function showAthorOpere($em,$idUtente,$idAutore){
         $connection = $em->getConnection();
            
            $statement = $connection->prepare("SELECT o.id,titolo,tecnica,o.data
                                                                                FROM (SELECT *
                                                                                              FROM opereinserite
                                                                                              WHERE id_utente=$idUtente) op JOIN opera o on op.id_opera=o.id
		
                                                                                WHERE id_autore=$idAutore");
            
            $statement->execute();
           
            // result contiene tutte le opere inserite dell'autore con id=$idAutore
            $results = $statement->fetchAll();
           
            return $results;
    }

    
    
    
}
