UserBundle\Entity\Utente:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\UtenteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nome:
            type: string
            length: 255
        cognome:
            type: string
            length: 255
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
